Test IPv4 and IPv6 floating IP assignment with dual stack
With these changes, and

    make k8s-test K8ST_TO_RUN=tests/test_simple.py:TestSimplePolicy

Prior to the CNI plugin fix at
https://github.com/projectcalico/cni-plugin/pull/922, the
test_simple_policy test failed with

    error: timed out waiting for the condition on pods/access

because the 'access' pod didn't start.  'kubectl describe' showed a
"mismatched IP versions" problem:

    Warning FailedCreatePodSandBox 12s (x5 over 60s) kubelet,
    kind-worker (combined from similar events): Failed to create pod
    sandbox: rpc error: code = Unknown desc = failed to setup network
    for sandbox
    "fede455cae2021942809745532d415bacd38214b94c86e4a85bc7d04418df9d6":
    error with field ExternalIP = '2001:67c:275c:ff::1' (mismatched IP
    versions)

Following the CNI plugin fix at
https://github.com/projectcalico/cni-plugin/pull/922, the test passes
again.