fix(docs): quickstart guide - separate out the taint commands
I propose to separate out the taints commands since when one fails, all fail:

```
a-vm:~$ kubectl taint nodes --all node-role.kubernetes.io/control-plane- node-role.kubernetes.io/master-
error: taint "node-role.kubernetes.io/master" not found
```

Turned out the only taint I had is "node-role.kubernetes.io/control-plane"
```
a-vm:~$ kubectl get nodes -o json | jq '.items[].spec'
{
  "podCIDR": "192.168.0.0/24",
  "podCIDRs": [
    "192.168.0.0/24"
  ],
  "taints": [
    {
      "effect": "NoSchedule",
      "key": "node-role.kubernetes.io/control-plane"
    }
  ]
}
```

So, this ran okay:
```
a-vm:~$ kubectl taint nodes --all node-role.kubernetes.io/control-plane-
node/nandaa-vm untainted
```