Don't bump netlink
Because then we get:

vendor/github.com/vishvananda/netlink/bridge_linux.go:22:27: undefined: unix.IFLA_EXT_MASK
vendor/github.com/vishvananda/netlink/bridge_linux.go:38:9: undefined: unix.IFLA_AF_SPEC
vendor/github.com/vishvananda/netlink/bridge_linux.go:90:21: undefined: unix.IFLA_AF_SPEC
vendor/github.com/vishvananda/netlink/link_linux.go:425:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:455:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:485:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:516:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:550:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:597:23: undefined: unix.IFLA_VFINFO_LIST
vendor/github.com/vishvananda/netlink/link_linux.go:721:23: undefined: unix.IFLA_NET_NS_FD
vendor/github.com/vishvananda/netlink/link_linux.go:721:23: too many errors