Prevent new DevStack from configuring a setting that old Tempest does not support
    Traceback (most recent call last):
      File "/opt/stack/tempest/.tox/venv/lib/python3.10/site-packages/oslo_config/cfg.py", line 2931, in _do_get
        return (convert(val), alt_loc)
      File "/opt/stack/tempest/.tox/venv/lib/python3.10/site-packages/oslo_config/cfg.py", line 2900, in convert
        return self._convert_value(
      File "/opt/stack/tempest/.tox/venv/lib/python3.10/site-packages/oslo_config/cfg.py", line 3028, in _convert_value
        return opt.type(value)
      File "/opt/stack/tempest/.tox/venv/lib/python3.10/site-packages/oslo_config/types.py", line 167, in __call__
        raise ValueError(
    ValueError: Valid values are [udhcpc, dhclient, ], but found 'dhcpcd'