Cherry pick #11743 for v3.31 branch
On the v3.31 branch, "UT/FV tests on new kernel" CI is failing and the artifacts show the same
problem as in #11743, i.e.:
```
docker buildx build --load --platform=linux/amd64 --pull --build-arg UBI_IMAGE=registry.access.redhat.com/ubi9/ubi-minimal:latest --build-arg GIT_VERSION=v3.31.3-44-gd4da4610c064-dirty --build-arg CALICO_BASE=calico/base:ubi9-1764972441 --build-arg BPFTOOL_IMAGE=calico/bpftool:v7.5.0 -t typha:latest-amd64 -f docker-image/Dockerfile docker-image
ERROR: failed to build: Error response from daemon: client version 1.52 is too new. Maximum supported API version is 1.41: driver not connecting
make[2]: *** [Makefile:118: .calico_typha.created-amd64] Error 1
make[2]: Leaving directory '/home/ubuntu/calico/typha'
make[1]: *** [Makefile:302: build-typha] Error 2
make[1]: Leaving directory '/home/ubuntu/calico/felix'
make: Leaving directory '/home/ubuntu/calico/felix'
make: *** [Makefile:384: fv-bpf] Error 2
```

It's not identical to the master branch because I think v3.31 is still using Focal, not Jammy.  But
trying the same fix, adapted for Focal.