Adapt test code for recent change in common Calico code
In the common Calico project code, 'validate_rules' (a utility
function) was just specialized into 'validate_profile' and
'validate_policy', and 'validate_rules' is no longer available, so
networking-calico's test_neutron_rule_to_etcd_rule_icmp test fails
with:

  File "networking_calico/plugins/ml2/drivers/calico/test/test_plugin_etcd.py", line 1017, in assertNeutronToEtcd
    common.validate_rules("profile_id", rules)
AttributeError: 'module' object has no attribute 'validate_rules'

This commit changes that test code to use validate_profile.

Change-Id: I061f6b996a5d0aaeada4329205aefac93ebbd622
Sem-Ver: bugfix