Revert "Add decorator to avoid SQL no transaction warning"
Because with the decorator present we get this ERROR traceback:

     Traceback (most recent call last):
       File "/opt/stack/data/venv/lib/python3.10/site-packages/eventlet/hubs/hub.py", line 471, in fire_timers
         timer()
       File "/opt/stack/data/venv/lib/python3.10/site-packages/eventlet/hubs/timer.py", line 59, in __call__
         cb(*args, **kw)
       File "/opt/stack/data/venv/lib/python3.10/site-packages/eventlet/greenthread.py", line 264, in main
         result = function(*args, **kwargs)
       File "/opt/stack/data/venv/lib/python3.10/site-packages/networking_calico/logutils.py", line 21, in wrapped
         return fn(*args, **kwargs)
       File "/opt/stack/data/venv/lib/python3.10/site-packages/networking_calico/plugins/ml2/drivers/calico/mech_calico.py", line 544, in _loop_writing_port_statuses
         self._try_to_update_port_status(admin_context, port_status_key)
       File "/opt/stack/data/venv/lib/python3.10/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 998, in wrapper
         return fn(*args, **kwargs)
       File "/opt/stack/data/venv/lib/python3.10/site-packages/networking_calico/plugins/ml2/drivers/calico/mech_calico.py", line 571, in _try_to_update_port_status
         self.db.update_port_status(admin_context,
       File "/opt/stack/neutron/neutron/plugins/ml2/plugin.py", line 2355, in update_port_status
         return self.update_port_statuses(
       File "/opt/stack/neutron/neutron/common/utils.py", line 721, in inner
         raise RuntimeError(_("Method %s cannot be called within a "
     RuntimeError: Method <function Ml2Plugin.update_port_statuses at 0x7bf071174af0> cannot be called within a transaction.

(which is obviously worse than the WARNING without the decorator)

This reverts commit 21a6f061f21c881d17401f9ff56b2af3bda97de9.