Update Ubuntu image for "new kernel" tests
CI has been showing this deprecation message:

    - The resource 'projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20200609' is deprecated. A suggested replacement is 'projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20210623'.

And this occasional flake:

    + gcloud --quiet compute ssh --zone=europe-west3-c ubuntu@sem-felix-56d03633-ut -- sudo apt-get update -y
    ...
    Get:43 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [528 B]
    Traceback (most recent call last):
      File "/usr/lib/cnf-update-db", line 26, in <module>
        col.create(db)
      File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 100, in create
        json.dump(self._calc_input_metadata(), fp)
      File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 114, in _calc_input_metadata
        st = os.stat(p)
    FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal-backports_universe_cnf_Commands-amd64'
    Fetched 19.4 MB in 4s (4,447 kB/s)
    Reading package lists...
    E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
    E: Sub-process returned an error code
    + echo 'Failed to create VM.  Tearing it down.'

Hoping an Ubuntu update will fix the latter as well as the former.