Address issues spotted by Copilot and CI on #11647
Copilot didn't run on #11577 because that was contributed from outside Tigera; but it did run when I
cherry-picked that PR to other branches, and spotted some minor issues that I'm fixing here.

I also noticed occurrences of the following TypeError in CI.  They don't cause any tests to fail,
because they occur in a spawned thread, but they look wrong:
```
Traceback (most recent call last):
  File "/code/.tox/py38/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 471, in fire_timers
    timer()
  File "/code/.tox/py38/lib/python3.8/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/code/.tox/py38/lib/python3.8/site-packages/eventlet/greenthread.py", line 264, in main
    result = function(*args, **kwargs)
  File "/code/networking_calico/plugins/ml2/drivers/calico/mech_calico.py", line 1118, in resync_monitor_thread
    if time_delta.total_seconds() > cfg.CONF.calico.resync_max_interval_secs:
TypeError: '>' not supported between instances of 'float' and 'MagicMock'
```
They occur because of the resync_monitor_thread being started in tests in test_mech_calico.py.  The
resync_monitor_thread isn't wanted for those tests, so let's suppress it.