Fix problems with tag detection and PBR version setting
We were seeing this:

   ValueError: git history requires a target version of
   pbr.version.SemanticVersion(3.9.2), but target version is
   pbr.version.SemanticVersion(3.8.4)

when building networking-calico packages from a commit with multiple
version tags.

The context for that was releasing a particular patch version, 3.8.4,
so the general fix is that when we know the version we're releasing,
skip the autodetection logic and just use that version.